[01-04 14:24:12] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 14:24:12] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 14_24_12
[01-04 14:24:12] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 14_24_12
[01-04 14:24:12] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 14_24_12
[01-04 14:24:12] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 14_24_12
[01-04 14:24:12] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 14_24_12
[01-04 14:24:20] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:24:20] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:24:22] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 14:24:24] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 14:24:32] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:32] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:32] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:32] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:32] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:32] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:33] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:34] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_5.zip'
[01-04 14:24:34] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_1.zip'
[01-04 14:24:34] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_7.zip'
[01-04 14:24:34] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_3.zip'
[01-04 14:24:34] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_2.zip'
[01-04 14:24:34] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_6.zip'
[01-04 14:24:35] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_4.zip'
[01-04 14:24:40] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:40] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:40] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:40] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:40] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:40] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:40] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:24:42] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_2.zip'
[01-04 14:24:42] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_5.zip'
[01-04 14:24:42] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_7.zip'
[01-04 14:24:42] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_1.zip'
[01-04 14:24:42] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_4.zip'
[01-04 14:24:42] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_3.zip'
[01-04 14:24:42] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_6.zip'
[01-04 14:24:46] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:25:53] [CBIGUtilities.py:469 -         upload_files()] INFO - Connection established ... 
[01-04 14:26:44] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 14:26:44] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 14_26_44
[01-04 14:26:44] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 14_26_44
[01-04 14:26:44] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 14_26_44
[01-04 14:26:44] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 14_26_44
[01-04 14:26:44] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 14_26_44
[01-04 14:26:50] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:26:50] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:26:52] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 14:26:53] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 14:27:00] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:00] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:00] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:00] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:00] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:00] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:00] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:02] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_1.zip'
[01-04 14:27:02] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_7.zip'
[01-04 14:27:03] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_3.zip'
[01-04 14:27:03] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_6.zip'
[01-04 14:27:03] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_2.zip'
[01-04 14:27:03] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_5.zip'
[01-04 14:27:03] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Delete_4.zip'
[01-04 14:27:07] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:07] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:07] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:07] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:07] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:07] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:07] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:27:09] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_3.zip'
[01-04 14:27:09] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_5.zip'
[01-04 14:27:09] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_1.zip'
[01-04 14:27:09] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_4.zip'
[01-04 14:27:09] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_6.zip'
[01-04 14:27:09] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_7.zip'
[01-04 14:27:09] [CBIGUtilities.py:444 -  upload_delete_files()] ERROR - [WinError 2] The system cannot find the file specified: 'C:\\Users\\khannapo\\OneDrive - Dun and Bradstreet\\Documents\\CBIG\\OutputFiles\\ReportToDews\\delete\\Insert_2.zip'
[01-04 14:27:13] [CBIGUtilities.py:434 -  upload_delete_files()] INFO - Connection established ... 
[01-04 14:28:20] [CBIGUtilities.py:469 -         upload_files()] INFO - Connection established ... 
[01-04 14:32:42] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 14:32:42] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 14_32_42
[01-04 14:32:42] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 14_32_42
[01-04 14:32:42] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 14_32_42
[01-04 14:32:42] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 14_32_42
[01-04 14:32:42] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 14_32_42
[01-04 14:32:50] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:32:50] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:32:52] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 14:32:53] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 14:33:38] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 14:33:38] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 14_33_38
[01-04 14:33:38] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 14_33_38
[01-04 14:33:38] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 14_33_38
[01-04 14:33:38] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 14_33_38
[01-04 14:33:38] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 14_33_38
[01-04 14:33:45] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:33:46] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:33:48] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 14:33:48] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 14:34:43] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 14:34:43] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 14_34_43
[01-04 14:34:43] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 14_34_43
[01-04 14:34:43] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 14_34_43
[01-04 14:34:43] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 14_34_43
[01-04 14:34:43] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 14_34_43
[01-04 14:34:48] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:34:48] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 14:34:50] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 14:34:51] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 14:34:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:34:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:34:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:34:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:34:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:34:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:34:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:36:05] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:36:05] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:36:05] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:36:05] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:36:05] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:36:05] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:36:05] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:36:07] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 14:36:07] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 14:36:07] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 14:36:07] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 14:36:07] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 14:36:07] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 14:36:07] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 14:36:12] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 14:37:20] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:21:53] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 21:21:53] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 21_21_53
[01-04 21:21:53] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 21_21_53
[01-04 21:21:53] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 21_21_53
[01-04 21:21:53] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 21_21_53
[01-04 21:21:53] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 21_21_53
[01-04 21:22:11] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:22:11] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:22:13] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 21:22:14] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 21:22:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:22:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:22:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:22:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:22:23] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:22:24] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:22:24] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:31] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:33] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:23:39] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:39] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:39] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:40] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:40] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:40] [CBIGUtilities.py:441 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:23:44] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:24:52] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:36:28] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 21:36:28] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 21_36_28
[01-04 21:36:28] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 21_36_28
[01-04 21:36:28] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 21_36_28
[01-04 21:36:28] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 21_36_28
[01-04 21:36:28] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 21_36_28
[01-04 21:36:44] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:36:45] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:36:46] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 21:36:48] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 21:36:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:36:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:36:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:36:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:36:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:36:56] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:36:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:04] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:06] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:10] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:38:12] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:12] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:12] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:12] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:12] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:12] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:12] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:12] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:38:17] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:40:04] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 21:40:04] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 21_40_04
[01-04 21:40:04] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 21_40_04
[01-04 21:40:04] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 21_40_04
[01-04 21:40:04] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 21_40_04
[01-04 21:40:04] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 21_40_04
[01-04 21:40:21] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:40:21] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:40:23] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 21:40:24] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 21:40:32] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:40:32] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:40:32] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:40:32] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:40:32] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:40:32] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:40:32] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:41:40] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:41:40] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:41:40] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:41:40] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:41:40] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:41:40] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:41:40] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:41:42] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:41:42] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:41:42] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:41:42] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:41:42] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:41:42] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:41:42] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:41:46] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:42:54] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:44:06] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 21:44:06] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 21_44_06
[01-04 21:44:06] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 21_44_06
[01-04 21:44:06] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 21_44_06
[01-04 21:44:06] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 21_44_06
[01-04 21:44:06] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 21_44_06
[01-04 21:44:18] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:44:19] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:44:20] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 21:44:21] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 21:44:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:44:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:44:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:44:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:44:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:44:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:44:29] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:37] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:39] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:45:43] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:54:21] [CBIGReportToDevws_v1.py:24 -             <module>()] INFO - *********************************START*****************************************************
[01-04 21:54:21] [CBIGReportToDevws_v1.py:26 -             <module>()] INFO - Process Started 04_01_2023 21_54_21
[01-04 21:54:21] [CBIGReportToDevws_v1.py:36 -             <module>()] INFO - Deleting Existing Csv files from output folder 04_01_2023 21_54_21
[01-04 21:54:21] [CBIGReportToDevws_v1.py:54 -             <module>()] INFO - Deleting Existing Excel files from Input folder 04_01_2023 21_54_21
[01-04 21:54:21] [CBIGReportToDevws_v1.py:58 -             <module>()] INFO - Files Deleted from input folder 04_01_2023 21_54_21
[01-04 21:54:21] [CBIGUtilities.py:31 -             __init__()] INFO - Files Deleted from output folder 04_01_2023 21_54_21
[01-04 21:54:37] [CBIGUtilities.py:122 -        download_file()] INFO - File name: Sample India Limited_ReportToDews_Template.xlsx_Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:54:38] [CBIGUtilities.py:255 - validate_input_files()] INFO - File In Process : Sample India Limited_ReportToDews_Template.xlsx
[01-04 21:54:40] [CBIGUtilities.py:230 -  managesqlconnection()] INFO - Data Stored : Process Completed
[01-04 21:54:41] [CBIGUtilities.py:356 - validate_input_files()] INFO - Validation Successfull
[01-04 21:54:49] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:54:49] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:54:49] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:54:49] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:54:49] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:54:49] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:54:49] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:55:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:55:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:55:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:55:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:55:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:55:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:55:57] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:55:59] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:55:59] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:55:59] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:55:59] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:55:59] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:55:59] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:55:59] [CBIGUtilities.py:442 -         upload_files()] ERROR - expected str, bytes or os.PathLike object, not list
[01-04 21:56:03] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
[01-04 21:57:11] [CBIGUtilities.py:431 -         upload_files()] INFO - Connection established ... 
